### ISSUE TITLE
Port-number setting in the Windows control panel has no effect

### ISSUE THREAD

**Issue by brtkrbzhnv** [Mach5/supersonic#61]
I've set the port number in the control panel to 58258, but it still (even after rebooting) listens on port 80 and not on port 58258.

Version 4.7.beta1 (build 09fa89fb36ee4ab1c483498c840d5dde95508237) – March 21, 2012
Server  jetty-6.1.x, java 1.6.0_31, Windows 7 (124.7 MB / 226.2 MB)

**Comment by timoreimann** [comment]
I don't happen to have a Windows instance installed which means that I cannot really test right now. I need to ask you this:

How do you start Supersonic on Windows? Do you possibly use the .bat file? If so, there's a SUPERSONIC_PORT parameter which you can change. You'll need to restart Supersonic in order for any change to take effect.

By the way, Supersonic should listen on port 4040 for HTTP traffic by default, so I think you somehow managed to change it to port 80 in the first place.

Sorry for not being able to provide better guidance due to a missing Windows instance on my side. If problems continue to persist, I'll see if I can install something on a virtual machine.

HTH,

--Timo

**Comment by brtkrbzhnv** [comment]
Thanks for the speedy and useful reply.

I was using the WAR version, so there was no .bat. It tried to use port #80 (which was not available) on the first launch, before I'd had any chance to change any settings. 

After seeing your reply, I uninstalled and then downloaded the standalone version with the .bat instead, and now it uses port #4040.

**Comment by timoreimann** [comment]
Glad you managed to get it to work by using the standalone version.

I guess we can close the issue for now.

**Comment by timoreimann** [comment]
Many Windows users seem to run into the problem, and the control panel should be usable for changing port numbers. Re-opening the issue therefore.

**Comment by timoreimann** [comment]
The bug has been fixed in the Windows installer version. The updated version is available in the [Supersonic Download section](https://github.com/Mach5/supersonic/downloads), or [directly here](https://github.com/downloads/Mach5/supersonic/supersonic-4.7.beta1-setup.exe).

Note that after installing the new Supersonic version, all settings applied previously (e.g., configured music directories, user accounts, etc.) can not be found anymore due to a required directory name change. To restore settings, follow this procedure:
- Stop Supersonic.
- Copy the contents of C:\subsonic into C:\supersonic.
- Restart Supersonic.

Afterwards, the C:\subsonic directory can be safely deleted.

All settings should be back. For troubleshooting help, please post on the [Supersonic User group](https://groups.google.com/forum/#!forum/supersonic-users).
