### ISSUE TITLE
No unit tests!

### ISSUE THREAD

**Issue by DBendit** [Mach5/supersonic#9]
The Android app has no unit tests whatsoever. We really need to fix this at some point to avoid regression issues.

**Comment by timoreimann** [comment]
Just removing the [Android] text label because we have a Github label now.

**Comment by timoreimann** [comment]
This is definitely something that I'd like to see as well. We should think about rules and conventions on how to use unit tests though. For instance, we'll hardly be able to enrich the existing (Subsonic) code base with unit tests due to the amount of code that would be necessary.

What I'd propose instead is to define a rule that no new code is added without unit tests. The two should strictly go together, i.e., code lacking unit tests won't be accepted, because it's simply too tempting to push a feature or bug fix to the master branch and hand in the unit tests "later". Moreover, the quality of code that's created along with unit tests or even in a TDD-ish way is simply better in my opinion.

What's your thoughts on this?
